version: '3.8'

services:
  # Our custom API server - connects to hosted Supabase
  api-server:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      SUPABASE_URL: https://xlvdasysekzforztqlds.supabase.co
      SUPABASE_SERVICE_ROLE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsdmRhc3lzZWt6Zm9yenRxbGRzIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1Mzk2NjQ5OSwiZXhwIjoyMDY5NTQyNDk5fQ.6FSKPcfmQr-OJwJ7oddkfyEsjLN7x5FipAd767U2OU4
      FRONTEND_URL: http://localhost:5173
    volumes:
      - ./server:/app
      - /app/node_modules

  # Frontend - connects to hosted Supabase and local API
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      VITE_SUPABASE_URL: https://xlvdasysekzforztqlds.supabase.co
      VITE_SUPABASE_ANON_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsdmRhc3lzZWt6Zm9yenRxbGRzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjY0OTksImV4cCI6MjA2OTU0MjQ5OX0.kzbZLHGUsX3nf-IfWj2zzSovTbMWjwA4m6463mFbgnU
      VITE_API_URL: http://localhost:3001
      VITE_WS_URL: http://localhost:3001
    depends_on:
      - api-server
